import { describe, expect, it, beforeEach, afterEach } from "vitest";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { parseBlocks } from "../src/parse.js";
import { buildDriftReport } from "../src/match.js";
import { weaveReport, writeWeave } from "../src/weave.js";

function makeReport(files: { source: string; text: string }[]) {
  const inputs = files.map((f) => ({
    source: f.source,
    blocks: parseBlocks(f.source, f.text),
  }));
  return buildDriftReport(inputs);
}

describe("weave", () => {
  let dir: string;

  beforeEach(async () => {
    dir = await fs.mkdtemp(path.join(os.tmpdir(), "rh-weave-"));
  });

  afterEach(async () => {
    await fs.rm(dir, { recursive: true, force: true });
  });

  it("merges aligned + reworded sections, picking longest when asked", async () => {
    const report = makeReport([
      {
        source: "AGENTS.md",
        text: "# Setup\n\nRun the thing.\n\n# Style\n\nUse spaces.\n",
      },
      {
        source: "CLAUDE.md",
        text: "# Setup\n\nRun the thing carefully and log output.\n\n# Style\n\nUse spaces.\n",
      },
    ]);

    const { markdown, sections } = await weaveReport(report, {
      pick: { kind: "longest" },
      omitHeader: true,
    });

    expect(sections).toHaveLength(2);
    expect(sections[0].headingPath).toEqual(["Setup"]);
    expect(sections[0].winnerSource).toBe("CLAUDE.md");
    expect(markdown).toContain("# Setup");
    expect(markdown).toContain("Run the thing carefully and log output.");
    expect(markdown).toContain("# Style");
    expect(markdown.endsWith("\n")).toBe(true);
  });

  it("honors --pick source= to force a specific winner", async () => {
    const report = makeReport([
      { source: "AGENTS.md", text: "# Rules\n\nA.\n" },
      { source: "CLAUDE.md", text: "# Rules\n\nB is longer than A.\n" },
    ]);

    const { sections } = await weaveReport(report, {
      pick: { kind: "source", source: "AGENTS.md" },
      omitHeader: true,
    });
    expect(sections[0].winnerSource).toBe("AGENTS.md");
    expect(sections[0].markdown).toContain("A.");
  });

  it("drops single-source blocks when onlyShared is set", async () => {
    const report = makeReport([
      { source: "AGENTS.md", text: "# Shared\n\nyes\n\n# Solo\n\nonly here\n" },
      { source: "CLAUDE.md", text: "# Shared\n\nyes\n" },
    ]);

    const shared = await weaveReport(report, {
      pick: { kind: "longest" },
      onlyShared: true,
      omitHeader: true,
    });
    expect(shared.sections.map((s) => s.key)).toEqual(["shared"]);
    expect(shared.skipped.some((s) => s.reason === "only-shared")).toBe(true);

    const full = await weaveReport(report, {
      pick: { kind: "longest" },
      omitHeader: true,
    });
    expect(full.sections.map((s) => s.key)).toEqual(["shared", "solo"]);
  });

  it("emits preamble before headed sections and preserves heading depth", async () => {
    const report = makeReport([
      {
        source: "AGENTS.md",
        text: "intro para\n\n# Top\n\nbody\n\n## Sub\n\nsubbody\n",
      },
      {
        source: "CLAUDE.md",
        text: "intro para\n\n# Top\n\nbody\n\n## Sub\n\nsubbody\n",
      },
    ]);

    const { markdown } = await weaveReport(report, {
      pick: { kind: "longest" },
      omitHeader: true,
    });

    const topIdx = markdown.indexOf("# Top");
    const subIdx = markdown.indexOf("## Sub");
    const introIdx = markdown.indexOf("intro para");
    expect(introIdx).toBeGreaterThanOrEqual(0);
    expect(introIdx).toBeLessThan(topIdx);
    expect(topIdx).toBeLessThan(subIdx);
  });

  it("writeWeave persists to disk atomically", async () => {
    const report = makeReport([
      { source: "AGENTS.md", text: "# One\n\nfoo\n" },
      { source: "CLAUDE.md", text: "# One\n\nfoo\n" },
    ]);

    const out = path.join(dir, "RULES.md");
    const { writtenTo, result } = await writeWeave(report, out, {
      pick: { kind: "longest" },
      cwd: dir,
      omitHeader: true,
    });
    expect(writtenTo).toBe(out);
    const onDisk = await fs.readFile(out, "utf8");
    expect(onDisk).toBe(result.markdown);
    expect(onDisk).toContain("# One");
  });

  it("includes a header + optional title when requested", async () => {
    const report = makeReport([
      { source: "AGENTS.md", text: "# X\n\na\n" },
      { source: "CLAUDE.md", text: "# X\n\na\n" },
    ]);
    const { markdown } = await weaveReport(report, {
      pick: { kind: "longest" },
      title: "Project Rules",
    });
    expect(markdown).toMatch(/^<!-- generated by rule-herder weave/);
    expect(markdown).toContain("# Project Rules");
    expect(markdown).toContain("# X");
  });

  it("returns an empty-but-valid document for an empty report", async () => {
    const report = makeReport([]);
    const { markdown, sections } = await weaveReport(report, {
      omitHeader: true,
    });
    expect(sections).toEqual([]);
    expect(markdown.endsWith("\n")).toBe(true);
  });
});
